apiVersion: v1
kind: Service
metadata:
  name: {{ include "fist.fullname" . }}
  labels:
    app: {{ template "fist.name" . }}
    chart: {{ template "fist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "fist.name" . }}
    release: {{ .Release.Name }}
