

pipeline {
    agent {
        label 'caltech'
    }
    environment {
        APPLICATION_NAME = "scheduling-manager"
        REPOSITORY="https://github.com/bbrown-caltech/capstone-hangout-point.git"
        GIT_CODE_PATH = "application/code/scheduling-manager"

        DOCKER_REGISTRY = 'docker.brianbrown.me'
        CREDENTIALS_ID = 'caltech'
        IMAGE_NAME = "docker.brianbrown.me/scheduling-manager"
        DOCKERFILE_PATH = "application/code/scheduling-manager/Dockerfile"

        HELM_REPOSITORY = "https://nexus.brianbrown.me/repository/helm/"
        HELM_IMAGE = 'docker.brianbrown.me/tools/debian-11/helm:3.7.0'

        DOCKER_IMAGE = ''
        IMAGE_TAG = ''
        CHART_VERSION = ''
        CHART_FILE_NAME = ''
        HELM_REPO_URL = ''
    }
    stages {
		/**************************************************************
		 *	RUN ALWAYS
		 **************************************************************/
		stage('Run Unit Tests') {
			steps {
				script {
					sh "echo \"Running unit tests...\""
				}
			}
		}
        stage('Build Docker Image') {
            steps {
               script {
                   //   Development Testing/Deployment
                   IMAGE_TAG = "develop";
                   //   Production Deployment
                   if ((BRANCH_NAME ==~/^(\d+\.\d+\.\d+)/)) {
                       IMAGE_TAG = BRANCH_NAME;
                   }
                   //   UAT Deployment
                   if ((BRANCH_NAME ==~/(main)/)) {
                       IMAGE_TAG = "latest";
                   }
                   DOCKER_IMAGE = docker.build("${IMAGE_NAME}", "--no-cache -f ./${DOCKERFILE_PATH} ./${GIT_CODE_PATH}/")
               }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry( "https://${DOCKER_REGISTRY}", "${CREDENTIALS_ID}" ) {
                        DOCKER_IMAGE.push("$IMAGE_TAG")
                    }
                }
            }
        }
		
		/**************************************************************
		 *	RUN ONLY AFTER MERGE INTO DEVELOP MAIN OR RELEASE TAGGED
		 **************************************************************/
        stage('Prepare to Build Helm Chart') {
            steps {
                script {
                    def YAML_FILE="/source/capstone-hangout-point/application/code/scheduling-manager/helm/scheduling-manager/Chart.yaml"
                    def CHART_PATH="/source/capstone-hangout-point/application/code/scheduling-manager/helm/scheduling-manager"
                    def CHART_PARENT_PATH="/source/capstone-hangout-point/application/code/scheduling-manager/helm"

                    docker.withRegistry( "https://${DOCKER_REGISTRY}", "${CREDENTIALS_ID}" ) {
                        docker.image(HELM_IMAGE).pull()
						
                        docker.image(HELM_IMAGE).inside("--entrypoint=") {
							
							stage('Getting Chart Version') {
							    def CHART_YAML_FILE="${CHART_PATH}/Chart.yaml"
								sh "git -C /source clone -b ${BRANCH_NAME} ${REPOSITORY}"
								CHART_VERSION=sh(script: "python /scripts/yaml_parser.py version ${CHART_YAML_FILE}", returnStdout: true)
							}
							
							stage('Packaging Helm Chart') {
								sh "helm package ${CHART_PATH} -d ${CHART_PARENT_PATH}"
								CHART_FILE_NAME="${CHART_PARENT_PATH}/${APPLICATION_NAME}-${CHART_VERSION}.tgz"
							}
							
							stage('Upload Helm Chart') {
								HELM_REPO_URL="${HELM_REPOSITORY}${APPLICATION_NAME}-${CHART_VERSION}.tgz"
								sh "curl -k -v -u 'caltech:Password123' --upload-file ${CHART_FILE_NAME} ${HELM_REPO_URL}"
							}
							
						}
						
                    }
                }
            }
        }
    }
    
}