version: '3.5'
services:

##########################################################################
#  CORE SERVICES
##########################################################################
  nginx:
    container_name: nginx
    image: ${NGINX}
    restart: unless-stopped
    networks:
      - simplilearn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/:/etc/nginx/
      - ./certs:/etc/nginx/certs

##########################################################################
#  CI/CD Application(s) and Service(s)
##########################################################################

  # Jenkins Nodes
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./docker-files/Jenkins.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    volumes:
      - jenkins_data:/var/jenkins_home:z
      - /etc/docker:/etc/docker
      - "/root/.docker:$HOME/.docker"
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  # Repository Manager
  nexus:
    container_name: nexus
    image: ${NEXUS}
    restart: unless-stopped
    networks:
      - simplilearn
    volumes:
      - nexus_data:/nexus-data:z

##########################################################################
#  CM Application(s) and Service(s)
##########################################################################
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: ./docker-files/Ansible.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    volumes:
      - ./config/ansible/playbooks:/playbooks
      - /usr/local/bin/kubectl:/usr/bin/kubectl


volumes:
  jenkins_data:
  nexus_data:

networks:
  simplilearn:
    driver: bridge