#
# Docker Compose configuration to stand up Clair services on a Jenkins node
#
# @author Mark DePalma
#  

version: '3.5'
services:
  postgres:
    image: arminc/clair-db:latest
    networks:
      - fmswf-clair
    volumes:
      - clair-postgres:/var/lib/postgresql/data
  clair:
    image: arminc/clair-local-scan:latest
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - fmswf-clair
  scanner:
    image: objectiflibre/clair-scanner:latest
    networks:
      - fmswf-clair
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  clair-postgres:

networks:
  fmswf-clair:
    driver: bridge