apiVersion: v1
kind: ConfigMap
metadata:
  name: book-my-show-config
  namespace: {{ .Values.configuration.namespace }}
  labels:
    name: book-my-show-config
    type: local
{{- with .Values.configuration }}
data:
{{ toYaml . | indent 2 }}
{{- end }}