@echo off

REM Adding a comment to trigger an automated Jenkins build

echo ...................................................................................
echo Removing Previous Image
echo ...................................................................................
docker rmi docker-fmswf.di2e.net/fmswf-applications/fms-intelligence-support-tool:develop

echo ...................................................................................
echo Building FIST Docker Image
echo ...................................................................................
docker build --no-cache -t docker-fmswf.di2e.net/fmswf-applications/fms-intelligence-support-tool:develop --build-arg BRANCH=%1 .

echo ...................................................................................
echo Pushing FIST Docker Image to DI2E
echo ...................................................................................
docker push docker-fmswf.di2e.net/fmswf-applications/fms-intelligence-support-tool:develop
